name: mpd-mini
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas-base
  - fiona
  - geopy
  - rtree
  - matplotlib-base
  - numpy
  - pandas
  - shapely
  - pytest
  - pytest-cov
  - meteostat=1.6.2
  - owlready2=0.38
  - haversine=2.7.0
  - exif=1.3.4

