name: movingpandas
channels:
  - conda-forge
dependencies:
  - python=3.10
  - black
  - cartopy
  - codecov
  - cython
  - hvplot
  - flake8
  - geopandas
  - geoviews
  - geopy
  - matplotlib
  - numpy
  - pandas
  - panel
  - pre-commit
  - pytest
  - pytest-cov
  - rasterio
  - scikit-learn
  - seaborn
  - shapely
  - stonesoup
    - meteostat=1.6.2
  - owlready2=0.38
  - haversine=2.7.0
  - exif=1.3.4

