name: movingpandas
channels:
  - conda-forge
  - zegami 
dependencies:
  - python=3.10
  - black
  - cartopy
  - codecov
  - cython
  - hvplot
  - flake8
  - geopandas
  - geoviews
  - geopy
  - matplotlib
  - numpy
  - pandas
  - panel
  - pre-commit
  - pytest
  - pytest-cov
  - rasterio
  - scikit-learn
  - seaborn
  - shapely
  - stonesoup
  - owlready2
  - haversine
  - pip:
    - meteostat
    - exif
    

